###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        restart: always
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=proyectosf5
            - MYSQL_DATABASE=databaseprueba
            - MYSQL_USER=ddbbprueba
            - MYSQL_PASSWORD=proyectosf5
        ports:
            - '38002:3306'

    webserver:
        restart: always
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '38000:80'

    php-fpm:
        restart: always
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: ddbbprueba
            PMA_PASSWORD: proyectosf5
        ports:
            - "38001:80"
        restart: always
            
